name: Bug report
description: File a bug report.
title: "[Bug] "
labels: ["new", "bug"]
assignees:
  - mkusz
body:
  - type: markdown
    attributes:
      value: |
        This is the form for reporting a bug.
        All bug reports helps me with making this project better for all the users.
        Thanks for taking the time and effort to fill out this form.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: |
        <sub>Markdown syntax is supported.</sub>

        Describe the problem
      placeholder: Describe the problem
    validations:
      required: true
  - type: textarea
    id: bug-expected
    attributes:
      label: Expected behaviour
      description: |
        <sub>Markdown syntax is supported.</sub>

        Describe the expected behavior.
      placeholder: Describe the expected bahavior
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        Below fields are optional, but can be very helpful, so please, spend a minute to fill them.
  - type: textarea
    id: bug-reproduction
    attributes:
      label: Bug description
      description: |
        <sub>Markdown syntax is supported.</sub>

        Describe the reproduction steps.
      placeholder: Describe the reproduction steps
    validations:
      required: false
  - type: dropdown
    id: system
    attributes:
      label: Operating system
      description: What operating system do you use?
      multiple: true
      options:
        - All
        - Windows
        - Linux
        - macOS
      default: 0
  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: What Python version do you use?
      multiple: true
      options:
        - All
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - Other
      default: 0
  - type: input
    id: repo-url
    attributes:
      label: Link to git repository
      description: Link to a repository where the bug is visible
      placeholder: ex. https://github.com/mkusz/mkdocs-publisher
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Build log output (console or from `*_mkdocs_build.log`)
      render: shell
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can I get in touch with you?
      placeholder: ex. email@example.com
    validations:
      required: false
