name: Feature request
description: File a feature request.
title: "[Feature] "
labels: ["new", "feature"]
assignees:
  - mkusz
body:
  - type: markdown
    attributes:
      value: |
        This is the form for reporting a feature request.
        All future requests helps me with making this project better for all the users.
        Thanks for taking the time and effort to fill out this form.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        <sub>Markdown syntax is supported.</sub>

        Describe the feature expected behaviour.
      placeholder: Describe the future request
      value: |
        **Future description**

    validations:
      required: true
  - type: dropdown
    id: plugin
    attributes:
      label: Project plugin
      description: What plugin feature request is related to?
      multiple: true
      options:
        - don't know
        - pub-blog
        - pub-debugger
        - pub-meta
        - pub-minifier
        - pub-obsidian
        - pub-social
        - a new plugin
        - external plugin integration
  - type: markdown
    attributes:
      value: |
        ---
        Below fields are optional, but can be very helpful, so please, spend a minute to fill them.
  - type: input
    id: additional-url
    attributes:
      label: Link
      description: External link where similar future is described
      placeholder: ex. https://quora.com/some-article/
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can I get in touch with you?
      placeholder: ex. email@example.com
    validations:
      required: false
