site_name: MkDocs Publisher
site_url: https://mkusz.github.io/mkdocs-publisher
site_author: Maciej 'maQ' Kusz
site_description: Blogging plugin for MkDocs
copyright: >
  &copy; 2023 Maciej 'maQ' Kusz

repo_url: https://github.com/mkusz/mkdocs-blog-in

use_directory_urls: true
#strict: true

dev_addr: 127.0.0.1:8666

extra:
  homepage: https://mkusz.github.io/mkdocs-blog-in
  version: 0.4.0

watch:
  - overrides

theme:
  name: material
  language: en
  custom_dir: overrides

  palette:
    primary: black
    accent: red

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer  # Prev/Next page

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - blog
  - minifier
